on:
  push:
    branches:
      - main
      - openfn/reconnect

jobs:
  deploy-to-lightning:
    runs-on: ubuntu-latest
    name: A job to deploy to Lightning
    steps:
      - name: openfn deploy
        uses: OpenFn/cli-deploy-action@v0.1.11
        with:
          secret_input: ${{ secrets.OPENFN_4adf2644_ed4e_4f97_a24c_ab35b3cb1efa_API_KEY }}
          config_path_input: ''
